name: NameDisplay
version: '$version'

main: me.stivendarsi.nameDisplay.NameDisplay
api-version: '26.1.1'
load: POSTWORLD
folia-supported: true
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false